"""
PXOS Kernel Plan Execution: The heart of agentic behavior.
This module interprets and applies plans generated by the AIBridge.
"""
from typing import Dict, Any, List

def install_memory_ops(context: Dict[str, Any]):
    """Installs a simple in-memory key-value store into the context."""
    context['memory'] = {}
    print("[KERNEL] In-memory store installed.")

def register_default_actions(context: Dict[str, Any]):
    """Registers default plan action handlers."""

    def action_new_doc(ctx, args):
        path = args.get('path', '/untitled')
        ctx['memory'][path] = ""
        print(f"[ACTION] new_doc: Created '{path}'")
        return {"ok": True, "path": path}

    def action_edit_text(ctx, args):
        path = args.get('path')
        if path not in ctx['memory']:
            return {"ok": False, "error": "file not found"}
        content = args.get('insert', '')
        ctx['memory'][path] += content
        print(f"[ACTION] edit_text: Inserted {len(content)} chars into '{path}'")
        return {"ok": True, "bytes_written": len(content)}

    def action_save(ctx, args):
        path = args.get('path')
        print(f"[ACTION] save: Saved '{path}' (simulation).")
        return {"ok": True, "size": len(ctx['memory'].get(path, ''))}

    context['actions'] = {
        'new_doc': action_new_doc,
        'edit_text': action_edit_text,
        'save': action_save,
    }
    print("[KERNEL] Default plan actions registered.")

def sys_plan_apply(context: Dict[str, Any], plan: Dict, dry_run: bool = False) -> Dict:
    """
    Applies a plan of actions to the system state.
    """
    if not plan or plan.get('version') != 'pxplan-1':
        return {"ok": False, "error": "Invalid or unsupported plan format."}

    actions = plan.get('actions', [])
    applied_count = 0
    rejected_count = 0
    effects = []

    print(f"[PLAN] Executing plan (dry_run={dry_run})...")
    for action_item in actions:
        action_name = action_item.get('action')
        handler = context.get('actions', {}).get(action_name)

        if handler:
            if not dry_run:
                result = handler(context, action_item.get('params', {}))
                effects.append(result)
            else:
                result = {"ok": True, "note": "dry_run"}

            if result.get("ok"):
                applied_count += 1
            else:
                rejected_count += 1
            print(f"  - Ran '{action_name}': {result}")
        else:
            rejected_count += 1
            effects.append({"ok": False, "error": f"Unknown action: {action_name}"})
            print(f"  - Rejected unknown action: '{action_name}'")

    result = {
        "ok": rejected_count == 0,
        "applied": applied_count,
        "rejected": rejected_count,
        "effects": effects
    }
    print(f"[PLAN] Execution finished: {result}")
    return result
